# Generated by Django 5.0 on 2024-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
