# Generated by Django 5.0 on 2024-01-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
